org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
neo_version=21.1.248
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_id=factorynetwork
mod_name=Factory Network
mod_version=0.1.0
mod_group_id=dev.devpanda.factorynetwork
mod_license=MIT
mod_authors=DevPanda
